@startuml Lab1.2_class_diagram

class Users {
    id: Integer,
    username: String,
    password: String,
    first_name: String,
    last_name: String,
    address: String,
    phone_number: String,
    role: String,
}

class Locations {
    id: Integer,
    name: String,
    nation: String,
    city: String,
}

class Restaurants {
    id: Integer,
    name: String,
    location_id: Integer,
    address: String,
    phone_number: String,
}

class Hotels {
    id: Integer,
    name: String,
    location_id: Integer,
    address: String,
    phone_number: String,
}

class Vist_Locations {
    id: Integer,
    name: String,
    location_id: Integer,
    address: String,
    phone_number: String,
}

class Tours {
    id: Integer,
    tour_guide_id: Integer,
    start_date: Date,
    end_date: Date,
}

class Tour_Locations {
    id: Integer,
    tour_id: Integer,
    vist_location_id: Integer,
    restaurant_id: Integer,
    hotel_id: Integer,
    start_time: Date,
    end_time: Date,
}

class Tour_Tourists {
    id: Integer,
    tour_id: Integer,
    tourist_id: Integer,
}

class Reviews {
    id: Integer,
    tour_id: String,
    user_id: String,
    stars: Integer,
    comment: String,
}

class Conversations {
    id: Integer,
    name: String,
    createdAt: Date,
    image: String,
}

class Conversation_Members {
    id: Integer,
    conversation_id: Integer,
    user_id: Integer,
}

class News {
    id: Integer,
    title: String,
    content: String,
    location_id: Integer,
    hotel_id: Integer,
    restaurant_id: Integer,
    vist_location_id: Integer,
}

class Bookings {
    id: Integer,
    tour_id: String,
    user_id: String,
    status: String,
}

@enduml
