@startuml liveInstructions_activity_diagram
|Hướng dẫn viên|
start
:(1) Chọn khách hàng cần hướng dẫn;
|Hệ thống|
if (Khách hàng đã chọn?) then (yes)
  |Cơ sở dữ liệu|
  :(2)Truy vấn thông tin về khách hàng;
  :(3) Lấy thông tin về khách hàng từ cơ sở dữ liệu;
  |Hệ thống|
  :(4) Bắt đầu cuộc hướng dẫn qua tin nhắn;
  |Cơ sở dữ liệu|
  :(5) Mở kết nối tin nhắn;
else (no)
  :(6) Hiển thị thông báo lỗi - Khách hàng chưa chọn;
endif

stop
@enduml