@startuml login_activity_diagram

|Người dùng|
start
repeat
  :(1) Người dùng nhập tên đăng nhập và mật khẩu;
  |Hệ thống|
  if (Thông tin hợp lệ?) then (yes)
    :(2) Hệ thống kiểm tra thông tin đăng nhập;
    |Cơ sở dữ liệu|
    if (Đúng tên đăng nhập và mật khẩu?) then (yes)
      :(3) Đăng nhập thành công;
      stop
    else (no)
      :(4) Hiển thị thông báo lỗi;
    endif
  else (no)
    :(5) Hiển thị thông báo lỗi;
  endif
repeat while (Thông tin không hợp lệ?);
stop

@enduml
