@startuml managePassengers_activity_diagram
|Hướng dẫn viên|
start
:(1) Chọn chức năng quản lý hành khách;
|Hệ thống|
|Cơ sở dữ liệu|
:(2) Truy vấn danh sách hành khách hiện tại;
|Hệ thống|
:(3) Hiển thị danh sách hành khách cho hướng dẫn viên;
|Hướng dẫn viên|
:(4) Thay đổi thông tin hành khách;
|Hệ thống|
|Cơ sở dữ liệu|
if (Danh sách hành khách đã thay đổi?) then (yes)
    :(5) Lưu danh sách hành khách mới vào cơ sở dữ liệu;
    |Hệ thống|
    :(6) Hiển thị thông báo - Danh sách hành khách đã được cập nhật;
else (no)
    |Hệ thống|
    :(7) Hiển thị thông báo - Không có thay đổi danh sách hành khách;
endif
|Hướng dẫn viên|

stop

@enduml
