@startuml provideFoodInfo_activity_diagram

|Hướng dẫn viên|
start
:(1) Chọn chức năng xem thông tin ẩm thực;

|Hệ thống|
if (Yêu cầu thông tin ẩm thực?) then (yes)
    |Cơ sở dữ liệu|
    :(2) Truy vấn dữ liệu ẩm thực;
    :(3) Lấy thông tin ẩm thực;
    |Hệ thống|
    :(4) Hiển thị thông tin ẩm thực cho người dùng;
else (no)
    :(5) Hiển thị thông báo lỗi - Yêu cầu không hợp lệ;

endif
stop
@enduml
