@startuml provideFoodInfo_activity_diagram

|Hướng dẫn viên|
start
:Chọn chức năng xem thông tin thực phẩm;

|Hệ thống|
if (Yêu cầu thông tin thực phẩm?) then (yes)
    |Cơ sở dữ liệu|
    :Truy vấn dữ liệu thực phẩm;
    :Lấy thông tin thực phẩm;
    |Hệ thống|
    :Hiển thị thông tin thực phẩm cho người dùng;
else (no)
    :Hiển thị thông báo lỗi - Yêu cầu không hợp lệ;

endif
stop
@enduml
