@startuml provideEmergencyService_activity_diagram
|Người dùng|
start
:(1) Chọn chức năng yêu cầu dịch vụ khẩn cấp;
|Hệ thống|
|Dịch vụ khẩn cấp|
if (Chức năng đã chọn?) then (yes)
  :(2) Người dùng nhập thông tin cần thiết;
  |Hệ thống|
  :(3) Gửi yêu cầu dịch vụ khẩn cấp tới dịch vụ khẩn cấp;
  |Dịch vụ khẩn cấp|
  :(4) Xử lý yêu cầu và cung cấp dịch vụ khẩn cấp;
  :(5) Liên lạc với người dùng để xác nhận thông tin;
  |Hệ thống|
  :(6) Xác nhận thông tin với người dùng;
  :(7) Hiển thị thông báo - Dịch vụ khẩn cấp đã được gửi;
else (no)
  :(8) Hiển thị thông báo lỗi - Chưa chọn chức năng yêu cầu dịch vụ khẩn cấp;
endif

stop
@enduml
