@startuml provideAccommodationInfo_activity_diagram

|Hướng dẫn viên|
start
:(1) Chọn chức năng xem thông tin nơi ở;

|Hệ thống|
if (Yêu cầu thông tin nơi ở?) then (yes)
    |Cơ sở dữ liệu|
    :(2) Truy vấn dữ liệu nơi ở;
    :(3) Lấy thông tin nơi ở;
    |Hệ thống|
    :(4) Hiển thị thông tin nơi ở cho hướng dẫn viên;
else (no)
    :(5) Hiển thị thông báo lỗi - Yêu cầu không hợp lệ;

endif
stop
@enduml
