@startuml provideWeatherInfo_activity_diagram

|Hướng dẫn viên|
start
:(1) Chọn chức năng xem thông tin thời tiết;

|Hệ thống|
if (Yêu cầu thông tin thời tiết?) then (yes)
    |Cơ sở dữ liệu|
    :(2) Truy vấn dữ liệu thời tiết;
    :(3) Lấy thông tin thời tiết từ dịch vụ thời tiết;
    |Hệ thống|
    :(4) Hiển thị thông tin thời tiết cho người dùng;
else (no)
    :(5) Hiển thị thông báo lỗi - Yêu cầu không hợp lệ;

endif
stop
@enduml
