@startuml review_activity_diagram
|Người dùng|
start
:(1) Kết thúc chuyến đi;
:(2) Chọn chức năng đánh giá chuyến đi;
|Hệ thống|
:(3) Hiển thị form đánh giá;
|Người dùng|
:(4) Nhập đánh giá và nhận xét;
|Cơ sở dữ liệu|
:(5) Lưu đánh giá và nhận xét vào cơ sở dữ liệu;
|Hệ thống|
:(6) Hiển thị thông báo - Đánh giá đã được ghi nhận;
stop
@enduml
